version: "3.8"

services:
  web:
    restart: always
    build: .
    working_dir: /code
    command: npm start
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - 6000:6000
    depends_on:
      - db
  db:
    image: postgres:16.1
    container_name: cms_business_manager
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cms_business_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Masinga*2024